### ISSUE TITLE
symoblic link level directory break move operation

### ISSUE THREAD

**Issue by chenghung** [marcojonker/data-elevator#2]
move top/ground will try to create level directory again if directory is symbolic link.

the fs.lstatsync(dirPath).isDirectory() return false if dirPath is a symbolic link

I think the correct way is using fs.realpathSync to fetch real path, then check the real path.

**Comment by marcojonker** [comment]
Hi Chenghung, thank you for the notification.

My solution is a bit different than your suggestion. 'lstatSync' not follow symlinks but 'statSync' does. I will create an update that uses 'statSync' instead of lstatSync.

Best regards,
Marco Jonker

**Comment by chenghung** [comment]
@marcojonker thanks for rapid fix.
